build: false

environment:
    PYTHON: "C:\\Python37"
    
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15

install:
  - set PATH=%PYTHON%;%PYTHON%/Scripts;%PATH%;
  - pip.exe install conan==1.11.0
  - pip.exe install conan_package_tools bincrafters_package_tools tqdm==4.28.1 pyparsing==2.3.0 wrapt==1.10.11 packaging==18.0
  - conan user # It creates the conan data directory

test_script:
  - python build.py
